version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_MAX_SIZE=100
      - CACHE_TTL_SECONDS=60
      - RATE_LIMIT_MAX=10
      - RATE_LIMIT_WINDOW_MS=60000
      - RATE_LIMIT_BURST_MAX=5
      - RATE_LIMIT_BURST_WINDOW_MS=10000
    depends_on:
      - redis
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data: